version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dashboard
      - frontend

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # if container name not provided then it will create automatically otherwise use this name
    container_name: quickshort-dashboard
    restart: unless-stopped
    environment:
      - VITE_URL_TRACKING_BASE_URL=http://quickshort.com

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    container_name: quickshort-frontend
    restart: unless-stopped
